version: 2.1

orbs:
  node: circleci/node@5.0

workflows:
  test_run:
    jobs:
      - node/run:
          app-dir: "/home/circleci/project/Team1-app" 
          pkg-manager: npm 
      - node/test:
          app-dir: "/home/circleci/project/Team1-app"
          version: '16.10'
          pkg-manager: npm
  mocha_test:
    jobs: 
      - mocha_test
# -store_test_results:
#     path: test-results
# -store_artifacts:
#     path: test-results


jobs:
  mocha_test:
    docker:
      - image: circleci/node:14
        auth:
          username: kurateam1
          password: kurapass1
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit