version: 2.1

orbs:
  node: circleci/node@5.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  test_run:
    jobs:
      - node/run:
          app-dir: "/home/circleci/project/Team1-app" 
          pkg-manager: npm 
      - node/test:
          app-dir: "/home/circleci/project/Team1-app"
          version: '16.10'
          pkg-manager: npm
  mocha_test:
    jobs: 
      - mocha_test
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          no-output-timeout: 20m
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: AWS_REGION
          repo: team1_project_repo
          skip-when-tags-exist: false
          tag: '${CIRCLE_BUILD_NUM}'
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results


jobs:
  mocha_test:
    docker:
      - image: circleci/node:14
        auth:
          username: kurateam1
          password: kurapass1
    steps:
      - checkout
      - run: npm install
      - run: npm install -g mocha
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit 
 