version: 2.1

orbs:
  node: circleci/node@5.0

workflows:
  test_run:
    jobs:
      - node/run:
          app-dir: "/home/circleci/project/Team1-app" 
          pkg-manager: npm 
      - node/test:
          app-dir: "/home/circleci/project/Team1-app"
          version: '16.10'
          pkg-manager: npm
-store_test_results:
    path: test-results
-store_artifacts:
    path: test-results

