version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
  
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
          context: terraform
      - terraform/validate:
          path: .
          context: terraform
      - terraform/plan:
          path: .
          context: terraform
      - terraform/apply:
          path: .
          context: terraform
      - terraform/destroy:
          path: .
          context: terraform
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
