version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0

workflows:
    terra check:
      jobs:
        - terraform/init
        - terraform/validate
        - terraform/plan
        - terraform/destroy